apiVersion: batch/v1
kind: Job
metadata:
  name: demo-job
  namespace: nginx
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: demo-job-pod
      labels:
        app: batch-task
    spec:
      containers:
        - name: demo-container
          image: busybox
          command: ["echo", "Hello from Kubernetes Job!"]
      restartPolicy: Never

